name: mymovies_app
description: My Movies app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  google_fonts: ^4.0.0
  intl: ^0.18.0
  path: ^1.8.3
  path_provider: ^2.1.4
  sqflite: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true
